name: exploregs
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.01.10
  - cffi=1.15.1
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - conda=23.1.0
  - conda-build=3.23.3
  - conda-content-trust=0.1.3
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - decorator=5.1.1
  - expat=2.4.9
  - ffmpeg=4.3
  - filelock=3.9.0
  - flit-core=3.6.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glob2=0.7
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - icu=58.2
  - idna=3.4
  - ipython=8.10.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libarchive=3.6.2
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.0.25
  - libcurand=10.3.2.56
  - libcurl=7.88.1
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblief=0.12.3
  - libnghttp2=1.46.0
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - ncurses=6.4
  - nettle=3.7.3
  - openh264=2.1.1
  - openssl=1.1.1t
  - parso=0.8.3
  - patch=2.7.6
  - patchelf=0.17.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - pkginfo=1.8.3
  - pluggy=1.0.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-lief=0.12.3
  - pycosat=0.6.4
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-libarchive-c=2.9
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pyyaml=6.0
  - readline=8.2
  - rhash=1.4.1
  - ripgrep=13.0.0
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - setuptools=65.6.3
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.1
  - stack_data=0.2.0
  - sympy=1.11.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - torchdata=0.6.0
  - torchtext=0.15.0
  - torchtriton=2.0.0
  - tqdm=4.64.1
  - traitlets=5.7.1
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - wheel=0.37.1
  - xz=5.2.10
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - accelerate==0.29.2
      - addict==2.4.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astroid==3.2.4
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==22.2.0
      - av==12.2.0
      - babel==2.16.0
      - bitsandbytes==0.43.1
      - bleach==6.1.0
      - blinker==1.8.2
      - certifi==2024.2.2
      - click==8.1.7
      - cmake==3.25.0
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - dash==2.18.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.8.7
      - defusedxml==0.7.1
      - diff-gaussian-rasterization==0.0.0
      - diff-surfel-rasterization==0.0.1
      - diffusers==0.30.0.dev0
      - dill==0.3.8
      - dnspython==2.3.0
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - exceptiongroup==1.1.1
      - executing==2.1.0
      - expecttest==0.1.4
      - fastjsonschema==2.20.0
      - flask==3.0.3
      - fonttools==4.53.1
      - fqdn==1.5.1
      - fsspec==2024.3.1
      - ftfy==6.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.23.5
      - hypothesis==6.70.0
      - imageio==2.34.1
      - imagesize==1.4.1
      - importlib-metadata==7.1.0
      - intel-openmp==2024.1.0
      - ipykernel==6.29.5
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - isort==5.13.2
      - itsdangerous==2.2.0
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiui==0.2.13
      - kiwisolver==1.4.7
      - kornia==0.6.12
      - lazy-loader==0.4
      - lit==15.0.7
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mediapy==1.2.2
      - mistune==3.0.2
      - mkl==2024.1.0
      - modified-diff-gaussian-rasterization==0.0.0
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.0
      - ninja==1.11.1.1
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - objprint==0.2.3
      - omegaconf==2.3.0
      - open3d==0.18.0
      - opencv-python==4.9.0.80
      - overrides==7.7.0
      - packaging==24.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - peft==0.10.0
      - pillow==9.5.0
      - platformdirs==4.3.2
      - plotly==5.24.1
      - plyfile==1.0.3
      - pointops2==1.0
      - prometheus-client==0.21.0
      - protobuf==4.25.3
      - pyee==11.1.0
      - pygments==2.18.0
      - pylint==3.2.7
      - pyparsing==3.1.4
      - pyppeteer==2.0.0
      - pyquaternion==0.9.9
      - pyre-extensions==0.0.29
      - python-dateutil==2.9.0.post0
      - python-etcd==0.4.5
      - python-json-logger==2.0.7
      - pytube==15.0.0
      - pyzmq==26.2.0
      - quickxorhash==1.0.5
      - referencing==0.35.1
      - regex==2023.12.25
      - requests==2.32.3
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.2
      - rpds-py==0.20.0
      - safetensors==0.4.2
      - scikit-image==0.23.2
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - simple-knn==0.0.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - tbb==2021.12.0
      - tenacity==9.0.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2024.5.22
      - tinycss2==1.3.0
      - tokenizers==0.15.2
      - tomli==2.0.1
      - tomlkit==0.13.2
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchelastic==0.2.2
      - torchmetrics==0.11.4
      - torchvision==0.15.2+cu118
      - tornado==6.4.1
      - transformers==4.39.3
      - trimesh==4.3.2
      - types-dataclasses==0.6.6
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.5.0
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - varname==0.13.5
      - wandb==0.16.6
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==10.4
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
      - xformers==0.0.20
      - zipp==3.18.1
